pr:
  autoCancel: "true"
  branches:
    include:
    - Test
    - main
  paths:
    exclude:
    - README.md
    - azure-pipelines.yml
stages:
- stage: TestSalesforceOrg
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/Test'))
  jobs:
  - job: DeployTestOrg
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
          checkLatest: true
      - bash: 
          npm install sfdx-cli --global
        displayName: Install Salesforce CLI
      - bash:
            sfdx config:set restDeploy=false --global
        displayName: Use SOAP API for Deployment
      - bash:
            sfdx force:auth:jwt:grant --clientid 3MVG9n_HvETGhr3BvDik7PR4zfJhjOIXLl7MaScI4ptSF8.0kOXNeMF7TrSvh0b7k5fxVIM9lckkGNktWIMLw --jwtkeyfile ./bin/server.key --username pitchaimuthu@fourbends.com --instanceurl https://fourbends-a-dev-ed.develop.lightning.force.com/
        displayName: Authorize Salesforce DeployTestOrg Org
      - bash:
            sfdx force:source:deploy -p force-app -w 10 -u pitchaimuthu@fourbends.com
        displayName: Deploy source code to DeployTestOrg Org
